name: Release 

on:
  create:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.6.0
        with: 
          dotnet-version: 3.1
      
      - name: Build Windows
        run: dotnet build -c Release -r win-x64 --no-self-contained
      
      - name: Build Linux
        run: dotnet build -c Release -r linux-x64 --no-self-contained
      
      - name: Build MacOS
        run: dotnet build -c Release -r osx-x64 --no-self-contained
      
      - name: Zip Windows
        uses: papeloto/action-zip@v1
        with:
          files: SendMail/bin/Release/netcoreapp3.1/win-x64
          dest: SendMail-Windows-x64.zip
      
      - name: Zip Linux
        uses: papeloto/action-zip@v1
        with:
          files: SendMail/bin/Release/netcoreapp3.1/linux-x64
          dest: SendMail-Linux-x64.zip
      
      - name: Zip MacOS
        uses: papeloto/action-zip@v1
        with:
          files: SendMail/bin/Release/netcoreapp3.1/osx-x64
          dest: SendMail-MacOS-x64.zip
